from aim_fsm import *

class e1(StateMachineProgram):

  def setup(self):
      # 
      #     check: ObjectCheck(OrangeBarrelObj)
      # 
      #     check =S=>
      #       Say("Visible")
      # 
      #     check =F=>
      #       Say("Nada")
      # 
      
      # Code generated by genfsm on Wed Jun 17 14:43:58 2026:
      
      check = ObjectCheck(OrangeBarrelObj) .set_name("check") .set_parent(self)
      say1 = Say("Visible") .set_name("say1") .set_parent(self)
      say2 = Say("Nada") .set_name("say2") .set_parent(self)
      
      successtrans1 = SuccessTrans() .set_name("successtrans1")
      successtrans1 .add_sources(check) .add_destinations(say1)
      
      failuretrans1 = FailureTrans() .set_name("failuretrans1")
      failuretrans1 .add_sources(check) .add_destinations(say2)
      
      return self
