from aim_fsm import *

class OrangeBarrelCheck(StateNode):
    def start(self, event=None):
        super().start(event)

        for obj in robot.world_map.objects.values():
            if isinstance(obj, OrangeBarrelObj) and obj.is_visible:
                self.post_success()
                return

        self.post_failure()


class Example2(StateMachineProgram):

    def setup(self):
        #         check: OrangeBarrelCheck()
        # 
        #         check =S=> orange
        #         check =F=> off
        # 
        #         orange: Glow(vex.LightType.ALL_LEDS, 250, 20, 0)
        #             =T(0.2)=> check
        # 
        #         off: Glow(vex.LightType.ALL_LEDS, 0, 0, 0)
        #             =T(0.2)=> check
        
        # Code generated by genfsm on Thu Jun 18 14:25:13 2026:
        
        check = OrangeBarrelCheck() .set_name("check") .set_parent(self)
        orange = Glow(vex.LightType.ALL_LEDS, 250, 20, 0) .set_name("orange") .set_parent(self)
        off = Glow(vex.LightType.ALL_LEDS, 0, 0, 0) .set_name("off") .set_parent(self)
        
        successtrans1 = SuccessTrans() .set_name("successtrans1")
        successtrans1 .add_sources(check) .add_destinations(orange)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(check) .add_destinations(off)
        
        timertrans1 = TimerTrans(0.2) .set_name("timertrans1")
        timertrans1 .add_sources(orange) .add_destinations(check)
        
        timertrans2 = TimerTrans(0.2) .set_name("timertrans2")
        timertrans2 .add_sources(off) .add_destinations(check)
        
        return self
